#!/usr/bin/env python3

import enlist, sys

UTF8 = usefile = False
end = ""

usage = """Usage:
    enlist f <filename> [args...]: Read from a file using the Enlist codepage

    enlist fu <filename> [args...]: Read from a file using UTF-8

    enlist e <code> [args...]: Read from the second command line input using the Enlist codepage

    enlist eu <code> [args...]: Read from the second command line input using UTF-8

    Append `n` to the flag to output with a trailing newline
"""

if len(sys.argv) < 3:
    raise SystemExit(usage)

for char in sys.argv[1]:
    if char == "f":
        usefile = True
    elif char == "u":
        UTF8 = True
    elif char == "n":
        end = "\n"

if usefile:
    with open(sys.argv[2], "rb") as file:
        code = file.read()
    if UTF8:
        code = code.decode("utf-8")
    else:
        code = "".join(jelly.code_page[ord(i)] for i in code)
else:
    code = sys.argv[2]
    if not UTF8:
        code = "".join(jelly.code_page[ord(i)] for i in code)

arguments = list(map(enlist.try_eval, sys.argv[3:]))

enlist.enlist_output(enlist.enlist_eval(code, arguments), end)
